# Generated by Django 3.2 on 2021-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='project_img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
